core/urls.py
from django.urls import include, path
from core.views import (
    index,
    category_list_view,
    product_list_view,
    product_detail_view,
    category_products_list_view,
    vendor_list_view,
    vendor_detail_view,
    tag_list_view,
    ajax_add_review,
    search_view,
    filter_products,
    add_to_cart,
    cart_view,
    delete_item_from_cart,
    update_item_from_cart,
    checkout_view,
    payment_completed_view,
    payment_failed_view,
    customer_dashboard,
    order_detail,
    make_default_address,
    add_to_wishlist,
    wishlist
    )

app_name = "core"
urlpatterns = [
    # Dashboard
    path("",index,name="index"),
    
    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_products_list_view, name="category-products-list"),
    
    # Products
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),
    
    # Tags
    path("products/tag/<tag_slug>/", tag_list_view, name="tag-list"),
    
    # Vendors
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    
    # add review
    path("ajax-add-review/<pid>/", ajax_add_review, name="ajax-add-review"),
    
    # search view
    path("search/",search_view,name="search"),
    
    # filter products
    path("filter-product/",filter_products,name="filter-product"),
    
    # add-to-cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    
    # cart-view
    path("cart/", cart_view, name="cart"),
    
    # delete cart items
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # update cart items
    path("update-from-cart/", update_item_from_cart, name="update-from-cart"),
    
    # checkout page
    path("checkout/", checkout_view, name="checkout"),
    
    # paypal payment
    # path("paypal/",include('paypal.standard.ipn.urls')),
    
    # payment successfull
    path("payment-completed/", payment_completed_view, name="payment-completed"),
    
    # payment failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    
    # user dashboard
    path("dashboard/", customer_dashboard, name="dashboard"),
    
    # order detail
    path("dashboard/order/<int:id>/", order_detail, name="order-detail"),
    
    # make default address
    path("dashboard/make-default-address/", make_default_address, name="make-default-address"),

    # make default address
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("wishlist/", wishlist, name="wishlist"),
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('core.urls')),
    path("user/",include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths.views import register_view, login_view, logout_view

app_name = "userauths"
urlpatterns = [
    path("sign-up/",register_view, name="sign-up"),
    path("sign-in/",login_view, name="sign-in"),
    path("sign-out/",logout_view, name="sign-out"),
]

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Review'}))
    
    class Meta:
        model=ProductReview
        fields = ['rating', 'review']

core/views.py
from django.shortcuts import get_object_or_404, redirect, render
from core.models import Products, Category, Vendor, CartOrder, CartOrderItems, Wishlist, Address, ProductImages, ProductReview
from taggit.models import Tag
from django.db.models import Avg
from core.forms import ProductReviewForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# from django.urls import reverse
# from django.conf import settings
# from django.views.decorators.csrf import csrf_exempt
# from paypal.standard.forms import PayPalPaymentsForm
# Create your views here.
def index(request):
    # products = Products.objects.all().order_by("-id")
    products = Products.objects.filter(product_status="published",featured=True).order_by("-id")
    context = {
        "products": products,
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Products.objects.filter(product_status="published")
    context = {
        "products": products
    }
    return render(request,'core/product-list.html',context)

def product_detail_view(request, pid):
    product = Products.objects.get(pid=pid)
    product_images = product.product_images.all()
    related_products = Products.objects.filter(category=product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by('-created_at')
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    review_form = ProductReviewForm()
    
    make_review = True
    
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user,product=product).count()
        
        if user_review_count > 0:
            make_review = False
    
    context = {
        "product": product,
        "product_images": product_images,
        "related_products": related_products,
        "reviews": reviews,
        "average_rating": average_rating,
        "review_form": review_form,
        "make_review": make_review,
    }
    return render(request,'core/product-detail.html',context)

def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request,'core/category-list.html',context)

def category_products_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Products.objects.filter(product_status="published",category=category)
    
    context = {
        'products':products,
        'category':category
    }
    return render(request,'core/category-products-list.html',context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors":vendors
    }
    return render(request,'core/vendor-list.html',context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Products.objects.filter(product_status="published",vendor=vendor)
    context = {
        "vendor":vendor,
        "products":products
    }
    return render(request,'core/vendor-detail.html',context)

def tag_list_view(request, tag_slug=None):
    products = Products.objects.filter(product_status="published").order_by("-id")
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
        
    context = {
        "products":products,
        "tag":tag
    }
    
    return render(request,"core/tag-list.html",context)

def ajax_add_review(request, pid):
    product = Products.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"]
    )
    
    
    context = {
        'user':user.username,
        'review':request.POST["review"],
        'rating':request.POST["rating"]
    }
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    return JsonResponse({
        'status': True,
        'context': context,
        'average_reviews': average_reviews
    })
    
def search_view(request):
    query = request.GET.get('q')
    
    products = Products.objects.filter(title__icontains=query,description__icontains=query).order_by("-created_at")
    
    context = {
        'products':products,
        'query':query
    }
    
    return render(request, "core/search.html", context)


def filter_products(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendors[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    
    products = Products.objects.filter(product_status="published").order_by('-id').distinct()
    
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)
    
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()
    
    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()
        
    context = {
        "products": products
    }
    data = render_to_string("core/async/product-list.html", context)
    
    return JsonResponse({'data':data})

def add_to_cart(request):
    cart_products = {}
    cart_products[str(request.GET['id'])] = {
        'pid':request.GET['pid'],
        'image':request.GET['image'],
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
    }
    
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_products[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_products) 
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_products
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        context = {
            "cart_data":request.session['cart_data_obj'],
            "totalcartitems": len(request.session['cart_data_obj']),
            "cart_total_amount": cart_total_amount
        }
        return render(request,"core/cart.html",context)
    else:
        messages.warning(request,"Your cart is empty.")
        return redirect("core:index")
        
def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = {
        "cart_data":request.session['cart_data_obj'],
        "totalcartitems": len(request.session['cart_data_obj']),
        "cart_total_amount": cart_total_amount
    }
    data = render_to_string("core/async/cart-list.html", context)
    
    return JsonResponse({'data':data, "totalcartitems": len(request.session['cart_data_obj'])})

def update_item_from_cart(request):
    product_id = str(request.GET['id'])
    qty = str(request.GET['qty'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(qty)
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = {
        "cart_data":request.session['cart_data_obj'],
        "totalcartitems": len(request.session['cart_data_obj']),
        "cart_total_amount": cart_total_amount
    }
    data = render_to_string("core/async/cart-list.html", context)
    
    return JsonResponse({'data':data, "totalcartitems": len(request.session['cart_data_obj'])})

@login_required
def checkout_view(request):
    # host = request.get_host()
    # paypal_dict = {
    #     "business": "19bmiit109@gmail.com",
    #     "amount": "10.00",
    #     "item_name": "Order item no : 4",
    #     "invoice": "INVOICE_3",
    #     "notify_url": 'http://{}{}'.format(host, reverse('core:paypal-ipn')),
    #     "return": 'http://{}{}'.format(host, reverse('core:payment-completed')),
    #     "cancel_return": 'http://{}{}'.format(host, reverse('core:payment-failed')),
    # }
    
    # paypal_payment_button = PayPalPaymentsForm(initial=paypal_dict)
    
    cart_total_amount = 0
    
    if 'cart_data_obj' in request.session:
        # for get total amount
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            
        order = CartOrder.objects.create(
            user=request.user,
            price=cart_total_amount
        )
        # store cart products

templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Shop
                <span></span> Checkout
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Checkout</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{totalcartitems}}</span> products in your cart</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7">
                <div class="row mb-50">
                    <!-- <div class="col-lg-6 mb-sm-15 mb-lg-0 mb-md-3">
                        <div class="toggle_info">
                            <span><i class="fi-rs-user mr-10"></i><span class="text-muted font-lg">Already have an account?</span> <a href="#loginform" data-bs-toggle="collapse" class="collapsed font-lg" aria-expanded="false">Click here to login</a></span>
                        </div>
                        <div class="panel-collapse collapse login_form" id="loginform">
                            <div class="panel-body">
                                <p class="mb-30 font-sm">If you have shopped with us before, please enter your details below. If you are a new customer, please proceed to the Billing &amp; Shipping section.</p>
                                <form method="post">
                                    <div class="form-group">
                                        <input type="text" name="email" placeholder="Username Or Email">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" placeholder="Password">
                                    </div>
                                    <div class="login_footer form-group">
                                        <div class="chek-form">
                                            <div class="custome-checkbox">
                                                <input class="form-check-input" type="checkbox" name="checkbox" id="remember" value="">
                                                <label class="form-check-label" for="remember"><span>Remember me</span></label>
                                            </div>
                                        </div>
                                        <a href="#">Forgot password?</a>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-md" name="login">Log in</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-lg-6">
                        <form method="post" class="apply-coupon">
                            <input type="text" placeholder="Enter Coupon Code...">
                            <button class="btn  btn-md" name="login">Apply Coupon</button>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <h4 class="mb-30">Billing Details</h4>
                    <div class="card-body border rounded mb-2">
                        <p>Name: {{ request.user }}</p>
                        <address>
                            Address: {{active_address.address}}
                        </address>
                        <p>Phone: {{active_address.contact}}</p>
                    </div>
                    <a href="{% url 'core:dashboard' %}" class="btn btn-fill-out btn-block mt-10 col-md-4">Change Address</a>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="border p-40 cart-totals ml-30 mb-50">
                    <div class="d-flex align-items-end justify-content-between mb-30">
                        <h4>Your Order</h4>
                        <h6 class="text-muted">Subtotal: ${{cart_total_amount|floatformat:2}}</h6>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mb-10">Back to cart<i class="fi-rs-shopping-cart ml-15"></i></a>
                    <div class="table-responsive order_table checkout">
                        <table class="table no-border">
                            <tbody>
                                {% for product_id,item in cart_data.items %}
                                    <tr>
                                        <td class="image product-thumbnail"><img src="{{item.image}}" alt="#"></td>
                                        <td>
                                            <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{item.title}}</a></h6></span>
                                            <!-- <div class="product-rate-cover">
                                                <div class="product-rate d-inline-block">
                                                    <div class="product-rating" style="width:90%">
                                                    </div>
                                                </div>
                                                <span class="font-small ml-5 text-muted"> (4.0)</span>
                                            </div> -->
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h5 class="text-body">${{item.price}} </h5>
                                        </td>
                                        <td>
                                            <h6 class="text-muted pl-20 pr-20">x {{item.qty}}</h6>
                                        </td>
                                        <td>
                                            <h4 class="text-brand">${% widthratio item.price 1 item.qty %}</h4>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="payment ml-30">
                    <h4 class="mb-30">Payment</h4>
                    <div class="payment_option">
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                            <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                            <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                        </div>
                        <div class="custome-radio">
                            <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5" checked="">
                            <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                        </div>
                    </div>
                    <div class="payment-logo d-flex">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                        <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                        <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                    </div>
                    <!-- <span class="btn btn-fill-out btn-block mt-30">{{paypal_payment_button.render}}</span> -->
                    <a href="{% url 'core:payment-completed' %}" class="btn btn-fill-out btn-block mt-30">Place an Order<i class="fi-rs-sign-out ml-15"></i></a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
    

templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<main class="main pages mb-80">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Vendors List
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        <div class="container">
            <div class="archive-header-2 text-center">
                <h1 class="display-2 mb-50">Vendors List</h1>
                <div class="row">
                    <div class="col-lg-5 mx-auto">
                        <div class="sidebar-widget-2 widget_search mb-50">
                            <div class="search-form">
                                <form action="#">
                                    <input type="text" placeholder="Search vendors (by name or ID)..." />
                                    <button type="submit"><i class="fi-rs-search"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-50">
                <div class="col-12 col-lg-8 mx-auto">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We have <strong class="text-brand">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Mall</a></li>
                                        <li><a href="#">Featured</a></li>
                                        <li><a href="#">Preferred</a></li>
                                        <li><a href="#">Total items</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row vendor-grid">
                
                {% for vendor in vendors %}
                <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                    <div class="vendor-wrap style-2 mb-40">
                        <div class="product-badges product-badges-position product-badges-mrg">
                            <span class="hot">Mall</span>
                        </div>
                        <div class="vendor-img-action-wrap">
                            <div class="vendor-img">
                                <a href="{% url 'core:vendor-detail' vendor.vid %}">
                                    <img class="default-img" src="{{vendor.image.url}}" alt="" />
                                </a>
                            </div>
                            <div class="mt-10">
                                <span class="font-small total-product">{{vendor.product.all.count}} products</span>
                            </div>
                        </div>
                        <div class="vendor-content-wrap">
                            <div class="mb-30">
                                <div class="product-category">
                                    <span class="text-muted">Since {{vendor.date|date:"Y"}}</span>
                                </div>
                                <h4 class="mb-5"><a href="{% url 'core:vendor-detail' vendor.vid %}">{{vendor.title}}</a></h4>
                                <div class="product-rate-cover">
                                    <div class="product-rate d-inline-block">
                                        <div class="product-rating" style="width: 90%"></div>
                                    </div>
                                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                                </div>
                                <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                    <ul class="contact-infor text-muted">
                                        <li><img src="{% static 'assets/imgs/theme/icons/icon-location.svg' %}" alt="" /><strong>Address: </strong> <span>{{vendor.address}}</span></li>
                                        <li><img src="{% static 'assets/imgs/theme/icons/icon-contact.svg' %}" alt="" /><strong>Call Us:</strong><span>{{vendor.contact}}</span></li>
                                    </ul>
                                    <a href="{% url 'core:vendor-detail' vendor.vid %}" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!--end vendor card-->
            </div>
            <div class="pagination-area mt-20 mb-20">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-start">
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                        <li class="page-item"><a class="page-link" href="#">6</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/core/wishlist.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
    
{% endblock content %}