core/urls.py
from django.urls import include, path
from core.views import (
    index,
    category_list_view,
    product_list_view,
    product_detail_view,
    category_products_list_view,
    vendor_list_view,
    vendor_detail_view,
    tag_list_view,
    ajax_add_review,
    search_view,
    filter_products,
    add_to_cart,
    cart_view,
    delete_item_from_cart,
    update_item_from_cart,
    checkout_view,
    payment_completed_view,
    payment_failed_view,
    customer_dashboard,
    order_detail,
    make_default_address,
    add_to_wishlist,
    wishlist
    )

app_name = "core"
urlpatterns = [
    # Dashboard
    path("",index,name="index"),
    
    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_products_list_view, name="category-products-list"),
    
    # Products
    path("products/", product_list_view, name="product-list"),
    path("products/<pid>/", product_detail_view, name="product-detail"),
    
    # Tags
    path("products/tag/<tag_slug>/", tag_list_view, name="tag-list"),
    
    # Vendors
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    
    # add review
    path("ajax-add-review/<pid>/", ajax_add_review, name="ajax-add-review"),
    
    # search view
    path("search/",search_view,name="search"),
    
    # filter products
    path("filter-product/",filter_products,name="filter-product"),
    
    # add-to-cart
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    
    # cart-view
    path("cart/", cart_view, name="cart"),
    
    # delete cart items
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # update cart items
    path("update-from-cart/", update_item_from_cart, name="update-from-cart"),
    
    # checkout page
    path("checkout/", checkout_view, name="checkout"),
    
    # paypal payment
    # path("paypal/",include('paypal.standard.ipn.urls')),
    
    # payment successfull
    path("payment-completed/", payment_completed_view, name="payment-completed"),
    
    # payment failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    
    # user dashboard
    path("dashboard/", customer_dashboard, name="dashboard"),
    
    # order detail
    path("dashboard/order/<int:id>/", order_detail, name="order-detail"),
    
    # make default address
    path("dashboard/make-default-address/", make_default_address, name="make-default-address"),

    # make default address
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("wishlist/", wishlist, name="wishlist"),
]

ecomm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('core.urls')),
    path("user/",include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Review'}))
    
    class Meta:
        model=ProductReview
        fields = ['rating', 'review']

core/views.py
from django.shortcuts import get_object_or_404, redirect, render
from core.models import Products, Category, Vendor, CartOrder, CartOrderItems, Wishlist, Address, ProductImages, ProductReview
from taggit.models import Tag
from django.db.models import Avg
from core.forms import ProductReviewForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# from django.urls import reverse
# from django.conf import settings
# from django.views.decorators.csrf import csrf_exempt
# from paypal.standard.forms import PayPalPaymentsForm
# Create your views here.
def index(request):
    # products = Products.objects.all().order_by("-id")
    products = Products.objects.filter(product_status="published",featured=True).order_by("-id")
    context = {
        "products": products,
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Products.objects.filter(product_status="published")
    context = {
        "products": products
    }
    return render(request,'core/product-list.html',context)

def product_detail_view(request, pid):
    product = Products.objects.get(pid=pid)
    product_images = product.product_images.all()
    related_products = Products.objects.filter(category=product.category).exclude(pid=pid)
    reviews = ProductReview.objects.filter(product=product).order_by('-created_at')
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    review_form = ProductReviewForm()
    
    make_review = True
    
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user,product=product).count()
        
        if user_review_count > 0:
            make_review = False
    
    context = {
        "product": product,
        "product_images": product_images,
        "related_products": related_products,
        "reviews": reviews,
        "average_rating": average_rating,
        "review_form": review_form,
        "make_review": make_review,
    }
    return render(request,'core/product-detail.html',context)

def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request,'core/category-list.html',context)

def category_products_list_view(request, cid):
    category = Category.objects.get(cid=cid)
    products = Products.objects.filter(product_status="published",category=category)
    
    context = {
        'products':products,
        'category':category
    }
    return render(request,'core/category-products-list.html',context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors":vendors
    }
    return render(request,'core/vendor-list.html',context)

def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Products.objects.filter(product_status="published",vendor=vendor)
    context = {
        "vendor":vendor,
        "products":products
    }
    return render(request,'core/vendor-detail.html',context)

def tag_list_view(request, tag_slug=None):
    products = Products.objects.filter(product_status="published").order_by("-id")
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
        
    context = {
        "products":products,
        "tag":tag
    }
    
    return render(request,"core/tag-list.html",context)

def ajax_add_review(request, pid):
    product = Products.objects.get(pk=pid)
    user = request.user
    
    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST["review"],
        rating=request.POST["rating"]
    )
    
    
    context = {
        'user':user.username,
        'review':request.POST["review"],
        'rating':request.POST["rating"]
    }
    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    
    return JsonResponse({
        'status': True,
        'context': context,
        'average_reviews': average_reviews
    })
    
def search_view(request):
    query = request.GET.get('q')
    
    products = Products.objects.filter(title__icontains=query,description__icontains=query).order_by("-created_at")
    
    context = {
        'products':products,
        'query':query
    }
    
    return render(request, "core/search.html", context)


def filter_products(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendors[]')
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    
    products = Products.objects.filter(product_status="published").order_by('-id').distinct()
    
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)
    
    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()
    
    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()
        
    context = {
        "products": products
    }
    data = render_to_string("core/async/product-list.html", context)
    
    return JsonResponse({'data':data})

def add_to_cart(request):
    cart_products = {}
    cart_products[str(request.GET['id'])] = {
        'pid':request.GET['pid'],
        'image':request.GET['image'],
        'title':request.GET['title'],
        'qty':request.GET['qty'],
        'price':request.GET['price'],
    }
    
    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_products[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_products) 
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_products
    return JsonResponse({"data":request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        context = {
            "cart_data":request.session['cart_data_obj'],
            "totalcartitems": len(request.session['cart_data_obj']),
            "cart_total_amount": cart_total_amount
        }
        return render(request,"core/cart.html",context)
    else:
        messages.warning(request,"Your cart is empty.")
        return redirect("core:index")
        
def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = {
        "cart_data":request.session['cart_data_obj'],
        "totalcartitems": len(request.session['cart_data_obj']),
        "cart_total_amount": cart_total_amount
    }
    data = render_to_string("core/async/cart-list.html", context)
    
    return JsonResponse({'data':data, "totalcartitems": len(request.session['cart_data_obj'])})

def update_item_from_cart(request):
    product_id = str(request.GET['id'])
    qty = str(request.GET['qty'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(qty)
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
            
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
    context = {
        "cart_data":request.session['cart_data_obj'],
        "totalcartitems": len(request.session['cart_data_obj']),
        "cart_total_amount": cart_total_amount
    }
    data = render_to_string("core/async/cart-list.html", context)
    
    return JsonResponse({'data':data, "totalcartitems": len(request.session['cart_data_obj'])})

@login_required
def checkout_view(request):
    # host = request.get_host()
    # paypal_dict = {
    #     "business": "19bmiit109@gmail.com",
    #     "amount": "10.00",
    #     "item_name": "Order item no : 4",
    #     "invoice": "INVOICE_3",
    #     "notify_url": 'http://{}{}'.format(host, reverse('core:paypal-ipn')),
    #     "return": 'http://{}{}'.format(host, reverse('core:payment-completed')),
    #     "cancel_return": 'http://{}{}'.format(host, reverse('core:payment-failed')),
    # }
    
    # paypal_payment_button = PayPalPaymentsForm(initial=paypal_dict)
    
    cart_total_amount = 0
    
    if 'cart_data_obj' in request.session:
        # for get total amount
        for pid, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
            
        order = CartOrder.objects.create(
            user=request.user,
            price=cart_total_amount
        )
        # store cart products

templates/core/async/cart-list.html
<main class="main" id="cart-list">
<div class="page-header breadcrumb-wrap">
    <div class="container">
        <div class="breadcrumb">
            <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
            <span></span> Shop
            <span></span> Cart
        </div>
    </div>
</div>
<div class="container mb-80 mt-50">
    <div class="row">
        <div class="col-lg-8 mb-40">
            <h1 class="heading-2 mb-10">Your Cart</h1>
            <div class="d-flex justify-content-between">
                <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="table-responsive shopping-summery">
                <table class="table table-wishlist">
                    <thead>
                        <tr class="main-heading">
                            <th class="custome-checkbox start pl-30">
                                <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                <label class="form-check-label" for="exampleCheckbox11"></label>
                            </th>
                            <th scope="col">Product</th>
                            <th scope="col">Title</th>
                            <th scope="col">Unit Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Subtotal</th>
                            <th scope="col">Refresh</th>
                            <th scope="col" class="end">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for product_id,item in cart_data.items %}
                            <tr class="pt-30">
                                <td class="custome-checkbox pl-30">
                                    <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                    <label class="form-check-label" for="exampleCheckbox1"></label>
                                </td>
                                <td class="image product-thumbnail pt-40"><img src="{{item.image}}" alt="#"></td>
                                <td class="product-des product-name">
                                    <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' item.pid %}">{{item.title}}</a></h6>
                                    <!-- <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width:90%">
                                            </div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div> -->
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-body">${{item.price}} </h4>
                                </td>
                                <td class="text-center detail-info" data-title="Stock">
                                    <div class="detail-extralink mr-15">
                                        <div class="detail-qty border radius p-0">    
                                            <span class="qty-val "><input type="number" name="qty" class="product-quantity-{{product_id}}" id="product-quantity-{{product_id}}" value="{{item.qty}}"></span>
                                        </div>
                                    </div>
                                </td>
                                <td class="price" data-title="Price">
                                    <h4 class="text-brand">${% widthratio item.price 1 item.qty %} </h4>
                                </td>
                                <td class="action text-center" data-title="Refresh"><button type="button" class="text-body border-0 bg-transparent update-cart-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></button></td>
                                <td class="action text-center" data-title="Remove"><button type="button" class="text-body border-0 bg-transparent delete-cart-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></button></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="divider-2 mb-30"></div>
            <div class="cart-action d-flex justify-content-between">
                <a class="btn "><i class="fi-rs-arrow-left mr-10"></i>Continue Shopping</a>
                <a class="btn  mr-10 mb-sm-15"><i class="fi-rs-refresh mr-10"></i>Update Cart</a>
            </div>
            <div class="row mt-50">
                <div class="col-lg-7">
                    <div class="calculate-shiping p-40 border-radius-15 border">
                        <h4 class="mb-10">Calculate Shipping</h4>
                        <p class="mb-30"><span class="font-lg text-muted">Flat rate:</span><strong class="text-brand">5%</strong></p>
                        <form class="field_form shipping_calculator">
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <div class="custom_select">
                                        <select class="form-control select-active w-100">
                                            <option value="">United Kingdom</option>
                                            <option value="AX">Aland Islands</option>
                                            <option value="AF">Afghanistan</option>
                                            <option value="AL">Albania</option>
                                            <option value="DZ">Algeria</option>
                                            <option value="AD">Andorra</option>
                                            <option value="AO">Angola</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row row">
                                <div class="form-group col-lg-6">
                                    <input required="required" placeholder="State / Country" name="name" type="text">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input required="required" placeholder="PostCode / ZIP" name="name" type="text">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="p-40">
                        <h4 class="mb-10">Apply Coupon</h4>
                        <p class="mb-30"><span class="font-lg text-muted">Using A Promo Code?</p>
                        <form action="#">
                            <div class="d-flex justify-content-between">
                                <input class="font-medium mr-15 coupon" name="Coupon" placeholder="Enter Your Coupon">
                                <button class="btn"><i class="fi-rs-label mr-10"></i>Apply</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="border p-md-4 cart-totals ml-30">
                <div class="table-responsive">
                    <table class="table no-border">
                        <tbody>
                            <tr>
                                <td class="cart_total_label">
                                    <h6 class="text-muted">Subtotal</h6>
                                </td>
                                <td class="cart_total_amount">
                                    <h4 class="text-brand text-end">${{ cart_total_amount|floatformat:2 }}</h4>
                                </td>
                            </tr>
                            <tr>
                                <td scope="col" colspan="2">
                                    <div class="divider-2 mt-10 mb-10"></div>
                                </td>
                            </tr>
                            <tr>
                                <td class="cart_total_label">
                                    <h6 class="text-muted">Shipping</h6>
                                </td>
                                <td class="cart_total_amount">
                                    <h5 class="text-heading text-end">Free</h4</td> </tr> <tr>
                                <td class="cart_total_label">
                                    <h6 class="text-muted">Estimate for</h6>
                                </td>
                                <td class="cart_total_amount">
                                    <h5 class="text-heading text-end">United Kingdom</h4</td> </tr> <tr>
                                <td scope="col" colspan="2">
                                    <div class="divider-2 mt-10 mb-10"></div>
                                </td>
                            </tr>
                            <tr>
                                <td class="cart_total_label">
                                    <h6 class="text-muted">Total</h6>
                                </td>
                                <td class="cart_total_amount">
                                    <h4 class="text-brand text-end">${{ cart_total_amount|floatformat:2 }}</h4>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
                {% if totalcartitems %}
                    <a href="#" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</main>

templates/core/async/product-list.html
{% for product in products %}
<div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
    <div class="product-cart-wrap mb-30">
        <div class="product-img-action-wrap">
            <div class="product-img product-img-zoom">
                <a href="{% url 'core:product-detail' product.pid %}">
                    <img class="default-img" src="{{ product.image.url }}" alt="" />
                    <img class="hover-img" src="{{ product.image.url }}" alt="" />
                </a>
            </div>
            <div class="product-action-1">
                <a aria-label="Add To Wishlist" class="action-btn" href="shop-wishlist.html"><i
                        class="fi-rs-heart"></i></a>
                <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                <a aria-label="Quick view" class="action-btn" data-bs-toggle="modal" data-bs-target="#quickViewModal"><i
                        class="fi-rs-eye"></i></a>
            </div>
            <div class="product-badges product-badges-position product-badges-mrg">
                <span class="hot">-{{ product.get_percentage|floatformat:0 }} % off</span>
            </div>
        </div>
        <div class="product-content-wrap">
            <div class="product-category">
                <a href="{% url 'core:category-products-list' product.category.cid %}">{{ product.category.title }}</a>
            </div>
            <h2>
                <a href="{% url 'core:product-detail' product.pid %}">{{product.title}}</a>
            </h2>
            <div class="product-rate-cover">
                <div class="product-rate d-inline-block">
                    <div class="product-rating" style="width: 90%"></div>
                </div>
                <span class="font-small ml-5 text-muted"> (4.0)</span>
            </div>
            <div>
                <span class="font-small text-muted">By
                    <a href="{% url 'core:vendor-detail' product.vendor.vid %}">{{ product.vendor.title }}</a></span>
            </div>
            <div class="product-card-bottom">
                <div class="product-price">
                    <span>${{product.price}}</span>
                    <span class="old-price">${{product.old_price}}</span>
                </div>
                <div class="add-cart">
                    <input type="hidden" name="product_quantity" class="product-quantity-{{product.id}}" value="1" />
                    <input type="hidden" name="product_pid" class="product-pid-{{product.id}}" value="{{ product.pid }}" />
                    <input type="hidden" name="product_id" class="product-id-{{product.id}}" value="{{ product.id }}" />
                    <input type="hidden" name="product_image" class="product-image-{{product.id}}" value="{{ product.image.url }}" />
                    <input type="hidden" name="product_title" class="product-title-{{product.id}}" value="{{ product.title }}" />
                    <input type="hidden" name="product_price" class="product-price-{{product.id}}" value="{{ product.price }}" />
                    <button class="add border-0 add-to-cart-btn" id="add-to-cart-btn" data-index="{{product.id}}"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}